version: "3.7"

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - milho
  app:
    restart: always
    build: 
      context: .
      args:
        DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@mysql:${DB_PORT}/${DB_DATABASE}'

    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      - mysql
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@mysql:${DB_PORT}/${DB_DATABASE}'
      MCMILHO_TOKEN: ${MCMILHO_TOKEN}
    networks:
      - milho
volumes:
  mysql-data:

networks:
  milho:
    driver: bridge